In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier

from sklearn.pipeline import make_pipeline

In [2]:
X,y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [3]:
model =make_pipeline(
    StandardScaler(), #car donnees numeriques
    SGDClassifier(max_iter=1000, tol=1e-3))
    
model.fit(X_train,y_train)
model.predict(X_test)
model.score(X_test,y_test)
model
    

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier', SGDClassifier())])

## Donnees Mixtes

In [4]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [5]:
y=titanic["survived"]
X=titanic.drop("survived",axis=1)

In [6]:
from sklearn.compose import make_column_transformer #va servir a faire le pretraitement des donnees mixtes




In [7]:
transformer = make_column_transformer((StandardScaler(), ["age","fare"]))

In [8]:
transformer.fit_transform(X)

array([[-0.53037664, -0.50244517],
       [ 0.57183099,  0.78684529],
       [-0.25482473, -0.48885426],
       ...,
       [        nan, -0.17626324],
       [-0.25482473, -0.04438104],
       [ 0.15850313, -0.49237783]])

In [9]:
from sklearn.compose import make_column_transformer

In [10]:
numerical_features = ["age", "fare"]
categorical_features = ["sex", "deck", "alone"]

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer




In [12]:
numerical_pipeline = make_pipeline(
    SimpleImputer(),
    StandardScaler()
)

categorical_pipeline = make_pipeline(
    SimpleImputer(strategy="most_frequent"),
    OneHotEncoder())

preprocessor = make_column_transformer(
    (numerical_pipeline, numerical_features),
    (categorical_pipeline, categorical_features)
)

In [13]:
model = make_pipeline(
    preprocessor,  SGDClassifier(max_iter=1000, tol=1e-3)
)
model.fit(X,y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer()),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['age', 'fare']),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder())]),
                                                  ['sex', 'deck', 'alone'])])),
                ('sgdclassifier', SGDClassifier())])

## Grand volume de donnees

In [14]:
y = titanic["survived"]
X = titanic.drop("survived", axis=1)

In [15]:
from sklearn.compose import make_column_selector
import numpy as np



In [16]:
numerical_features = make_column_selector(dtype_include=np.number)
categorical_features = make_column_selector(dtype_exclude=np.number)

In [18]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer


numerical_pipeline = make_pipeline(
    SimpleImputer(),
    StandardScaler()
)

categorical_pipeline = make_pipeline(
    SimpleImputer(strategy="most_frequent"),
    OneHotEncoder())

preprocessor = make_column_transformer(
    (numerical_pipeline, numerical_features),
    (categorical_pipeline, categorical_features)
)

In [19]:
model = make_pipeline(
    preprocessor,  SGDClassifier(max_iter=1000, tol=1e-3)
)
model.fit(X,y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer()),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000023616EB3980>),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000023616EB18B0>)])),
                ('sgdclassifier', SGDClassifier())])

## Imputation des valeurs manquantes

In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import SGDClassifier

In [21]:
from sklearn.impute import SimpleImputer

In [22]:
X= np.array([[10,3],
             [0,4],
             [5,3],
             [np.nan,3]])

In [23]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit_transform(X)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

## KNN Imputer

In [24]:
from sklearn.impute import KNNImputer


In [25]:
X = np.array([[10,100],
              [0,4],
              [5,3],
              [np.nan,20]])  

In [26]:
imputer = KNNImputer(n_neighbors=3)
imputer.fit_transform(X)

array([[ 10., 100.],
       [  0.,   4.],
       [  5.,   3.],
       [  5.,  20.]])